from ikea_furniture_database_structure import Furniture, Wardrobe, Desk, TV_Cabinet, engine
from sqlmodel import Session
import json

# 示範數據
# Wardrobe 數據        
ikea_wardrobes = [
    {
        "product_id": "W001",
        "name": "PAX",
        "brand": "IKEA",
        "color": "White",
        "style": "Modern",
        "materials": "Particleboard",
        "category": "Wardrobes",
        "length": 200.0,
        "width": 60.0,
        "height": 236.0,
        "weight": 45.5,
        "serial_no": 1001,
        "country_of_origin": "Sweden",
        "price": 299.99,
        "warranty": 10,
        "assembly_require": False,
        "have_stock": True,
        "qc": True,
        "depth_length": 58.0,
        "hanging": True,
        "structure": "Modular",
        "function_features": "Adjustable Shelves",
        "installation": "Wall-mounted",
        "load_capacity": "50 kg",
        "advanced_technologies": ["Soft-closing hinges"]
    },
    {
        "product_id": "W002",
        "name": "BRIMNES",
        "brand": "IKEA",
        "color": "Black-Brown",
        "style": "Contemporary",
        "materials": "Fiberboard",
        "category": "Wardrobes",
        "length": 180.0,
        "width": 55.0,
        "height": 220.0,
        "weight": 30.0,
        "serial_no": 1002,
        "country_of_origin": "China",
        "price": 199.50,
        "warranty": 10,
        "assembly_require": False,
        "have_stock": True,
        "qc": True,
        "depth_length": 50.0,
        "hanging": True,
        "structure": "Freestanding",
        "function_features": "Mirrored Doors",
        "installation": "Free-standing",
        "load_capacity": "40 kg",
        "advanced_technologies": []
    },
    {
        "product_id": "W003",
        "name": "PLATSA",
        "brand": "IKEA",
        "color": "Oak Veneer",
        "style": "Scandinavian",
        "materials": "Wood",
        "category": "Wardrobes",
        "length": 150.0,
        "width": 55.0,
        "height": 200.0,
        "weight": 25.0,
        "serial_no": 1003,
        "country_of_origin": "Poland",
        "price": 149.99,
        "warranty": 5,
        "assembly_require": False,
        "have_stock": True,
        "qc": True,
        "depth_length": 53.0,
        "hanging": False,
        "structure": "Modular",
        "function_features": "Drawers Included",
        "installation": "Wall-mounted",
        "load_capacity": "30 kg",
        "advanced_technologies": []
    },
    {
        "product_id": "W004",
        "name": "KLEPPSTAD",
        "brand": "IKEA",
        "color": "Gray",
        "style": "Minimalist",
        "materials": "Metal/Glass",
        "category": "Wardrobes",
        "length": 160.0,
        "width": 50.0,
        "height": 210.0,
        "weight": 20.5,
        "serial_no": 1004,
        "country_of_origin": "Germany",
        "price": 89.99,
        "warranty": 10,
        "assembly_require": False,
        "have_stock": True,
        "qc": True,
        "depth_length": 48.0,
        "hanging": True,
        "structure": "Frame with doors",
        "function_features": "Glass Doors",
        "installation": "Free-standing",
        "load_capacity": "25 kg",
        "advanced_technologies": []
    },
    {
        "product_id": "W005",
        "name": "ALGOT",
        "brand": "IKEA",
        "color": "Stainless Steel",
        "style": "Industrial",
        "materials": "Metal",
        "category": "Wardrobes",
        "length": 140.0,
        "width": 45.0,
        "height": 190.0,
        "weight": 15.0,
        "serial_no": 1005,
        "country_of_origin": "USA",
        "price": 79.99,
        "warranty": 5,
        "assembly_require": False,
        "have_stock": True,
        "qc": True,
        "depth_length": 40.0,
        "hanging": True,
        "structure": "Wall system",
        "function_features": "Customizable Uprights",
        "installation": "Wall-mounted",
        "load_capacity": "20 kg",
        "advanced_technologies": []
    },
    {
        "product_id": "W006",
        "name": "HEMNES",
        "brand": "IKEA",
        "color": "Red",
        "style": "Traditional",
        "materials": "Solid Pine",
        "category": "Wardrobes",
        "length": 170.0,
        "width": 60.0,
        "height": 215.0,
        "weight": 40.0,
        "serial_no": 1006,
        "country_of_origin": "Vietnam",
        "price": 249.99,
        "warranty": 10,
        "assembly_require": False,
        "have_stock": True,
        "qc": True,
        "depth_length": 55.0,
        "hanging": True,
        "structure": "Freestanding",
        "function_features": "Shoe Storage",
        "installation": "Free-standing",
        "load_capacity": "45 kg",
        "advanced_technologies": []
    },
    {
        "product_id": "W007",
        "name": "NORDLI",
        "brand": "IKEA",
        "color": "Dark Blue",
        "style": "Mid-Century",
        "materials": "Wood/Metal",
        "category": "Wardrobes",
        "length": 190.0,
        "width": 65.0,
        "height": 240.0,
        "weight": 55.0,
        "serial_no": 1007,
        "country_of_origin": "Sweden",
        "price": 349.99,
        "warranty": 10,
        "assembly_require": False,
        "have_stock": True,
        "qc": True,
        "depth_length": 60.0,
        "hanging": True,
        "structure": "Modular",
        "function_features": "LED Lighting",
        "installation": "Wall-mounted",
        "load_capacity": "60 kg",
        "advanced_technologies": ["Motion Sensor Lights"]
    },
    {
        "product_id": "W008",
        "name": "BOAXEL",
        "brand": "IKEA",
        "color": "Green",
        "style": "Rustic",
        "materials": "Bamboo",
        "category": "Wardrobes",
        "length": 130.0,
        "width": 40.0,
        "height": 180.0,
        "weight": 10.0,
        "serial_no": 1008,
        "country_of_origin": "Indonesia",
        "price": 69.99,
        "warranty": 5,
        "assembly_require": False,
        "have_stock": True,
        "qc": True,
        "depth_length": 35.0,
        "hanging": False,
        "structure": "Freestanding",
        "function_features": "Foldable Design",
        "installation": "Free-standing",
        "load_capacity": "15 kg",
        "advanced_technologies": []
    },
    {
        "product_id": "W009",
        "name": "TYSsedal",
        "brand": "IKEA",
        "color": "Beige",
        "style": "Classic",
        "materials": "Plywood",
        "category": "Wardrobes",
        "length": 165.0,
        "width": 58.0,
        "height": 205.0,
        "weight": 28.0,
        "serial_no": 1009,
        "country_of_origin": "Malaysia",
        "price": 129.99,
        "warranty": 10,
        "assembly_require": False,
        "have_stock": True,
        "qc": True,
        "depth_length": 50.0,
        "hanging": True,
        "structure": "Sliding Doors",
        "function_features": "Shoe Rack",
        "installation": "Free-standing",
        "load_capacity": "35 kg",
        "advanced_technologies": []
    },
    {
        "product_id": "W010",
        "name": "SLARHÖLL",
        "brand": "IKEA",
        "color": "Yellow",
        "style": "Retro",
        "materials": "Plastic/Metal",
        "category": "Wardrobes",
        "length": 155.0,
        "width": 52.0,
        "height": 195.0,
        "weight": 18.5,
        "serial_no": 1010,
        "country_of_origin": "Turkey",
        "price": 89.99,
        "warranty": 5,
        "assembly_require": False,
        "have_stock": True,
        "qc": True,
        "depth_length": 45.0,
        "hanging": False,
        "structure": "Cube System",
        "function_features": "Removable Bins",
        "installation": "Wall-mounted",
        "load_capacity": "25 kg",
        "advanced_technologies": []
    }
]
# Desk 數據
ikea_desks = [
    {
        "product_id": "D001",
        "name": "BEKANT",
        "brand": "IKEA",
        "color": "White",
        "style": "Modern",
        "materials": "Particleboard",
        "category": "Desk",
        "length": 160.0,
        "width": 80.0,
        "height": 72.0,
        "weight": 30.5,
        "serial_no": 2001,
        "country_of_origin": "Sweden",
        "price": 199.99,
        "warranty": 5,
        "assembly_require": False,
        "have_stock": True,
        "qc": True,
        "design_feature": "Adjustable height",
        "ergonomics": "Ergonomic edge",
        "additional_options": "Cable management"
    },
    {
        "product_id": "D002",
        "name": "MICKE",
        "brand": "IKEA",
        "color": "Black-Brown",
        "style": "Contemporary",
        "materials": "Fiberboard",
        "category": "Desk",
        "length": 105.0,
        "width": 50.0,
        "height": 75.0,
        "weight": 25.0,
        "serial_no": 2002,
        "country_of_origin": "China",
        "price": 99.99,
        "warranty": 2,
        "assembly_require": False,
        "have_stock": True,
        "qc": True,
        "design_feature": "Compact design",
        "ergonomics": "Rounded corners",
        "additional_options": "Integrated drawer"
    },
    {
        "product_id": "D003",
        "name": "MALM",
        "brand": "IKEA",
        "color": "Oak Veneer",
        "style": "Scandinavian",
        "materials": "Wood",
        "category": "Desk",
        "length": 140.0,
        "width": 65.0,
        "height": 73.0,
        "weight": 28.0,
        "serial_no": 2003,
        "country_of_origin": "Poland",
        "price": 149.99,
        "warranty": 10,
        "assembly_require": False,
        "have_stock": True,
        "qc": True,
        "design_feature": "Pull-out panel",
        "ergonomics": "Soft-closing drawers",
        "additional_options": "File storage"
    },
    {
        "product_id": "D004",
        "name": "LINNMON",
        "brand": "IKEA",
        "color": "Gray",
        "style": "Minimalist",
        "materials": "Particleboard/Steel",
        "category": "Desk",
        "length": 120.0,
        "width": 60.0,
        "height": 70.0,
        "weight": 15.0,
        "serial_no": 2004,
        "country_of_origin": "Germany",
        "price": 49.99,
        "warranty": 1,
        "assembly_require": False,
        "have_stock": True,
        "qc": True,
        "design_feature": "Lightweight",
        "ergonomics": "Smooth surface",
        "additional_options": "Leg attachments"
    },
    {
        "product_id": "D005",
        "name": "TROTTEN",
        "brand": "IKEA",
        "color": "Stained Oak",
        "style": "Industrial",
        "materials": "Steel/Wood",
        "category": "Desk",
        "length": 150.0,
        "width": 75.0,
        "height": 72.0,
        "weight": 40.0,
        "serial_no": 2005,
        "country_of_origin": "USA",
        "price": 179.99,
        "warranty": 5,
        "assembly_require": False,
        "have_stock": True,
        "qc": True,
        "design_feature": "Electric height adjustment",
        "ergonomics": "Memory preset buttons",
        "additional_options": "Sturdy frame"
    },
    {
        "product_id": "D006",
        "name": "ALEX",
        "brand": "IKEA",
        "color": "Turquoise",
        "style": "Retro",
        "materials": "Plywood/Plastic",
        "category": "Desk",
        "length": 100.0,
        "width": 55.0,
        "height": 70.0,
        "weight": 18.5,
        "serial_no": 2006,
        "country_of_origin": "Vietnam",
        "price": 129.99,
        "warranty": 3,
        "assembly_require": False,
        "have_stock": True,
        "qc": True,
        "design_feature": "Built-in organizer",
        "ergonomics": "Sliding drawer",
        "additional_options": "Lockable compartment"
    },
    {
        "product_id": "D007",
        "name": "VITTSJÖ",
        "brand": "IKEA",
        "color": "Black",
        "style": "Modern",
        "materials": "Glass/Metal",
        "category": "Desk",
        "length": 110.0,
        "width": 55.0,
        "height": 75.0,
        "weight": 22.0,
        "serial_no": 2007,
        "country_of_origin": "Italy",
        "price": 89.99,
        "warranty": 2,
        "assembly_require": False,
        "have_stock": True,
        "qc": True,
        "design_feature": "Floating design",
        "ergonomics": "Tempered glass surface",
        "additional_options": "Wall anchors included"
    },
    {
        "product_id": "D008",
        "name": "KULLABERG",
        "brand": "IKEA",
        "color": "Natural Bamboo",
        "style": "Rustic",
        "materials": "Bamboo/Steel",
        "category": "Desk",
        "length": 130.0,
        "width": 70.0,
        "height": 74.0,
        "weight": 20.0,
        "serial_no": 2008,
        "country_of_origin": "Indonesia",
        "price": 159.99,
        "warranty": 5,
        "assembly_require": False,
        "have_stock": True,
        "qc": True,
        "design_feature": "Curved edges",
        "ergonomics": "Anti-slip surface",
        "additional_options": "Monitor stand"
    },
    {
        "product_id": "D009",
        "name": "FREDDE",
        "brand": "IKEA",
        "color": "Black/Red",
        "style": "Gaming",
        "materials": "Particleboard/Plastic",
        "category": "Desk",
        "length": 160.0,
        "width": 85.0,
        "height": 150.0,
        "weight": 50.0,
        "serial_no": 2009,
        "country_of_origin": "China",
        "price": 249.99,
        "warranty": 5,
        "assembly_require": False,
        "have_stock": True,
        "qc": True,
        "design_feature": "Multi-level design",
        "ergonomics": "Cable organizers",
        "additional_options": "Headphone hook"
    },
    {
        "product_id": "D010",
        "name": "SKARSTA",
        "brand": "IKEA",
        "color": "Birch",
        "style": "Functional",
        "materials": "Solid Wood",
        "category": "Desk",
        "length": 120.0,
        "width": 70.0,
        "height": 72.0,
        "weight": 35.0,
        "serial_no": 2010,
        "country_of_origin": "Norway",
        "price": 139.99,
        "warranty": 10,
        "assembly_require": False,
        "have_stock": True,
        "qc": True,
        "design_feature": "Manual crank adjustment",
        "ergonomics": "Spacious work area",
        "additional_options": "Drawer unit compatibility"
    }
]
# TV Cabinet 數據
ikea_tv_cabinets = [
    {  "product_id": "TV001",
        "name": "LACK",
        "brand": "IKEA",
        "color": "Black",
        "style": "Modern",
        "materials": "Particleboard",
        "category": "TV_Cabinet",
        "length": 160.0,
        "width": 40.0,
        "height": 50.0,
        "weight": 25.5,
        "serial_no": 3001,
        "country_of_origin": "Sweden",
        "price": 79.99,
        "warranty": 2,
        "assembly_require": False,
        "have_stock": True,
        "qc": True,
        "design_feature": "Minimalist floating design",
        "compatibility": "Up to 65-inch TVs",
        "additional_features": "Cable management holes"
    },
    {   "product_id": "TV002",
        "name": "FJÄLLBO",
        "brand": "IKEA",
        "color": "Dark Gray",
        "style": "Industrial",
        "materials": "Steel/Wood",
        "category": "TV_Cabinet",
        "length": 140.0,
        "width": 45.0,
        "height": 48.0,
        "weight": 35.0,
        "serial_no": 3002,
        "country_of_origin": "China",
        "price": 129.99,
        "warranty": 5,
        "assembly_require": False,
        "have_stock": True,
        "qc": True,
        "design_feature": "Metal frame construction",
        "compatibility": "Up to 75-inch TVs",
        "additional_features": "Adjustable shelf levels"
    },
    {
        "product_id": "TV003",
        "name": "BERGSNÄS",
        "brand": "IKEA",
        "color": "Oak Veneer",
        "style": "Scandinavian",
        "materials": "Plywood",
        "category": "TV_Cabinet",
        "length": 180.0,
        "width": 50.0,
        "height": 55.0,
        "weight": 28.0,
        "serial_no": 3003,
        "country_of_origin": "Poland",
        "price": 149.99,
        "warranty": 10,
        "assembly_require": False,
        "have_stock": True,
        "qc": True,
        "design_feature": "Hidden storage compartment",
        "compatibility": "Up to 70-inch TVs",
        "additional_features": "Soft-close drawers"
    },
    {
        "product_id": "TV004",
        "name": "BRIMNES",
        "brand": "IKEA",
        "color": "White",
        "style": "Contemporary",
        "materials": "Fiberboard",
        "category": "TV_Cabinet",
        "length": 120.0,
        "width": 38.0,
        "height": 45.0,
        "weight": 18.0,
        "serial_no": 3004,
        "country_of_origin": "Vietnam",
        "price": 89.99,
        "warranty": 3,
        "assembly_require": False,
        "have_stock": True,
        "qc": True,
        "design_feature": "Integrated glass doors",
        "compatibility": "Up to 55-inch TVs",
        "additional_features": "LED lighting system"
    },
    {
        "product_id": "TV005",
        "name": "HEMNES",
        "brand": "IKEA",
        "color": "Dark Blue",
        "style": "Traditional",
        "materials": "Solid Pine",
        "category": "TV_Cabinet",
        "length": 200.0,
        "width": 55.0,
        "height": 60.0,
        "weight": 40.0,
        "serial_no": 3005,
        "country_of_origin": "Lithuania",
        "price": 199.99,
        "warranty": 5,
        "assembly_require": False,
        "have_stock": True,
        "qc": True,
        "design_feature": "Cabinet with paneled fronts",
        "compatibility": "Up to 85-inch TVs",
        "additional_features": "Lockable storage"
    },
    {
        "product_id": "TV006",
        "name": "LÖVBACKEN",
        "brand": "IKEA",
        "color": "Walnut",
        "style": "Mid-Century",
        "materials": "Wood/Metal",
        "category": "TV_Cabinet",
        "length": 150.0,
        "width": 42.0,
        "height": 52.0,
        "weight": 30.5,
        "serial_no": 3006,
        "country_of_origin": "Germany",
        "price": 169.99,
        "warranty": 5,
        "assembly_require": False,
        "have_stock": True,
        "qc": True,
        "design_feature": "Tapered legs",
        "compatibility": "Up to 60-inch TVs",
        "additional_features": "Heat-resistant surface"
    },
    {
        "product_id": "TV007",
        "name": "KALLAX",
        "brand": "IKEA",
        "color": "Turquoise",
        "style": "Modern",
        "materials": "Particleboard",
        "category": "TV_Cabinet",
        "length": 147.0,
        "width": 39.0,
        "height": 57.0,
        "weight": 22.0,
        "serial_no": 3007,
        "country_of_origin": "USA",
        "price": 69.99,
        "warranty": 2,
        "assembly_require": False,
        "have_stock": True,
        "qc": True,
        "design_feature": "Cube storage system",
        "compatibility": "Up to 50-inch TVs",
        "additional_features": "Convertible to room divider"
    },
    {
        "product_id": "TV008",
        "name": "BESTÅ",
        "brand": "IKEA",
        "color": "High-Gloss Black",
        "style": "Modern",
        "materials": "Foil/Wood",
        "category": "TV_Cabinet",
        "length": 180.0,
        "width": 48.0,
        "height": 58.0,
        "weight": 45.0,
        "serial_no": 3008,
        "country_of_origin": "China",
        "price": 259.99,
        "warranty": 10,
        "assembly_require": False,
        "have_stock": True,
        "qc": True,
        "design_feature": "Wall-mounted configuration",
        "compatibility": "Up to 80-inch TVs",
        "additional_features": "Integrated sound system space"
    },
    {
        "product_id": "TV009",
        "name": "MALM",
        "brand": "IKEA",
        "color": "Birch",
        "style": "Minimalist",
        "materials": "Fiberboard",
        "category": "TV_Cabinet",
        "length": 190.0,
        "width": 50.0,
        "height": 45.0,
        "weight": 33.0,
        "serial_no": 3009,
        "country_of_origin": "Sweden",
        "price": 139.99,
        "warranty": 5,
        "assembly_require": False,
        "have_stock": True,
        "qc": True,
        "design_feature": "Sliding door mechanism",
        "compatibility": "Up to 65-inch TVs",
        "additional_features": "Hidden cable organizer"
    },
    {
        "product_id": "TV010",
        "name": "TROGEN",
        "brand": "IKEA",
        "color": "Light Gray",
        "style": "Rustic",
        "materials": "Reclaimed Wood",
        "category": "TV_Cabinet",
        "length": 170.0,
        "width": 47.0,
        "height": 53.0,
        "weight": 38.5,
        "serial_no": 3010,
        "country_of_origin": "Thailand",
        "price": 179.99,
        "warranty": 5,
        "assembly_require": False,
        "have_stock": True,
        "qc": True,
        "design_feature": "Distressed wood finish",
        "compatibility": "Up to 70-inch TVs",
        "additional_features": "Wine rack integration"
    }
]
def import_data():
    with Session(engine) as session:
        # 導入Wardrobes
        for data in ikea_wardrobes:
            furniture = Furniture(
                product_id=data["product_id"],
                category="Wardrobes",
                brand=data["brand"],
                name=data["name"],
                color=data["color"],
                style=data["style"],
                materials=data["materials"],
                length=data["length"],
                width=data["width"],
                height=data["height"],
                weight=data["weight"],
                serial_no=data["serial_no"],
                country_of_origin=data["country_of_origin"],
                price=data["price"],
                warranty=data["warranty"],
                assembly_require=data["assembly_require"],
                have_stock=data["have_stock"],
                qc=data["qc"],
            )
            session.add(furniture)
            session.commit()
            
            ward_data = {k: data[k] for k in data if k in Wardrobe.__fields__}
            ward_data["advanced_technologies"] = json.dumps(data["advanced_technologies"])
            wardrobe = Wardrobe(**ward_data)
            session.add(wardrobe)
            session.commit()

        # 導入Desks
        for data in ikea_desks:
            # Fix category name
            data["category"] = "Desk"
            furniture = Furniture(
                product_id=data["product_id"],
                category=data["category"],
                brand=data["brand"],
                name=data["name"],
                color=data["color"],
                style=data["style"],
                materials=data["materials"],
                length=data["length"],
                width=data["width"],
                height=data["height"],
                weight=data["weight"],
                serial_no=data["serial_no"],
                country_of_origin=data["country_of_origin"],
                price=data["price"],
                warranty=data["warranty"],
                assembly_require=data["assembly_require"],
                have_stock=data["have_stock"],
                qc=data["qc"],
            )
            session.add(furniture)
            session.commit()

            desk_data = {
                "product_id": data["product_id"],
                "design_features": data["design_feature"],  # 鍵名修正
                "ergonomics": data["ergonomics"],
                "additional_options": data["additional_options"]
            }
            desk = Desk(**desk_data)
            session.add(desk)
            session.commit()

        # 導入TV Cabinets
        for data in ikea_tv_cabinets:
            # Fix category name
            data["category"] = "TV_Cabinet"
            furniture = Furniture(
                product_id=data["product_id"],
                category=data["category"],
                brand=data["brand"],
                name=data["name"],
                color=data["color"],
                style=data["style"],
                materials=data["materials"],
                length=data["length"],
                width=data["width"],
                height=data["height"],
                weight=data["weight"],
                serial_no=data["serial_no"],
                country_of_origin=data["country_of_origin"],
                price=data["price"],
                warranty=data["warranty"],
                assembly_require=data["assembly_require"],
                have_stock=data["have_stock"],
                qc=data["qc"],
            )
            session.add(furniture)
            session.commit()

            tv_data = {
                "product_id": data["product_id"],
                "design_features": data["design_feature"],  # 鍵名修正
                "compatibility": data["compatibility"],
                "additional_features": data["additional_features"]
            }
            tv_cabinet = TV_Cabinet(**tv_data)
            session.add(tv_cabinet)
            session.commit()

if __name__ == "__main__":
    import_data()